# Generated by Django 4.0.6 on 2022-07-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_image',
            new_name='profile_picture',
        ),
    ]
